export const venues = [
  {
    id: "heritage",
    name: "Lagos",
    subtitle: "Lekki bridge · lagoon lights",
    level: 1,
    skin: 0,
    entry: 50,
    mood: "Where every great run begins.",
  },
  {
    id: "riviera",
    name: "London",
    subtitle: "Westminster · clock tower",
    level: 2,
    skin: 1,
    entry: 100,
    mood: "Cool cloth. Clear focus.",
  },
  {
    id: "regent",
    name: "Paris",
    subtitle: "Eiffel Tower · evening lights",
    level: 3,
    skin: 2,
    entry: 250,
    mood: "A room for the composed player.",
  },
  {
    id: "midnight",
    name: "Tokyo",
    subtitle: "Torii gate · lantern glow",
    level: 4,
    skin: 3,
    entry: 500,
    mood: "Make your mark after dark.",
  },
  {
    id: "jade",
    name: "Dubai",
    subtitle: "Burj skyline · desert glow",
    level: 5,
    skin: 4,
    entry: 1000,
    mood: "Precision in perfect balance.",
  },
  {
    id: "champion",
    name: "New York",
    subtitle: "Manhattan · city lights",
    level: 7,
    skin: 5,
    entry: 2500,
    mood: "A table you earn.",
  },
];
export const challenges = [
  {
    id: "pocket",
    name: "Find the pocket",
    drill: "pocket",
    description: "Pot the 1 ball. Start with a gentle, straight stroke.",
    targets: [1],
    xp: 100,
    coins: 100,
    difficulty: "FOUNDATION",
  },
  {
    id: "finish",
    name: "The final black",
    drill: "finish",
    description: "Sink the 8 and finish with confidence.",
    targets: [8],
    xp: 100,
    coins: 100,
    difficulty: "FOUNDATION",
  },
  {
    id: "cut",
    name: "Read the angle",
    drill: "cut",
    description: "Cut the 1 ball into a pocket.",
    targets: [1],
    xp: 100,
    coins: 150,
    difficulty: "CONTROL",
  },
  {
    id: "spin",
    name: "Cue-ball craft",
    drill: "spin",
    description: "Use position and spin to pocket the 1.",
    targets: [1],
    xp: 100,
    coins: 150,
    difficulty: "CONTROL",
  },
  {
    id: "open",
    name: "Build a run",
    drill: "open",
    description: "Pocket the 1, 2 and 3 in one visit. Avoid scratching.",
    targets: [1, 2, 3],
    xp: 100,
    coins: 200,
    difficulty: "PRECISION",
  },
  {
    id: "break",
    name: "Opening statement",
    drill: "break",
    description: "Pot at least one object ball on the break.",
    targets: [],
    xp: 100,
    coins: 200,
    difficulty: "POWER",
  },
];
const venueByCity: Record<string, string> = {
  lagos: "heritage",
  london: "riviera",
  paris: "regent",
  tokyo: "midnight",
  dubai: "jade",
  newyork: "champion",
};
/** Two trick shots per venue. Clearing both stamps the city in the player's passport. */
const city = (
  venue: string,
  label: string,
  n: number,
  name: string,
  description: string,
  targets: number[],
) => ({
  id: `${venue}-${n}`,
  name,
  drill: `${venue}-${n}`,
  description,
  targets,
  xp: 50,
  coins: 75,
  difficulty: label.toUpperCase(),
  city: venueByCity[venue],
});
export const cityChallenges = [
  city(
    "lagos",
    "Lagos",
    1,
    "Bridge crossing",
    "A long straight pot across the lagoon. Keep it smooth.",
    [1],
  ),
  city(
    "lagos",
    "Lagos",
    2,
    "Lagoon kick",
    "The 9 blocks the line. Kick off a cushion into the 1.",
    [1],
  ),
  city(
    "london",
    "London",
    1,
    "Rail runner",
    "A thin cut along the rail into the corner.",
    [1],
  ),
  city(
    "london",
    "London",
    2,
    "Clock-face combo",
    "Play the 2 into the 1. Only the 1 needs to drop.",
    [1],
  ),
  city(
    "paris",
    "Paris",
    1,
    "Tower cut",
    "A steep cut on the 1 into the side pocket.",
    [1],
  ),
  city(
    "paris",
    "Paris",
    2,
    "Evening run",
    "Pocket the 1, 2 and 3 in one visit.",
    [1, 2, 3],
  ),
  city(
    "tokyo",
    "Tokyo",
    1,
    "Lantern draw",
    "Pot the 1, then draw the cue ball back for the 8.",
    [1, 8],
  ),
  city(
    "tokyo",
    "Tokyo",
    2,
    "Torii gate",
    "Thread the cue ball between the posts to pot the 1.",
    [1],
  ),
  city(
    "dubai",
    "Dubai",
    1,
    "Desert length",
    "The longest pot on the table, corner to corner.",
    [1],
  ),
  city(
    "dubai",
    "Dubai",
    2,
    "Skyline run",
    "Two pots, one visit, no scratch.",
    [1, 2],
  ),
  city(
    "newyork",
    "New York",
    1,
    "Manhattan cut",
    "The thinnest cut in the packs. Commit to it.",
    [1],
  ),
  city(
    "newyork",
    "New York",
    2,
    "City lights",
    "The 8 sits in the middle. Pot the 1, 2 and 3 around it.",
    [1, 2, 3],
  ),
];
/** Drill name to target balls, for everything the referee can replay. */
export const drillTargets: Record<string, number[]> = Object.fromEntries(
  [...challenges, ...cityChallenges].map((c) => [c.drill, c.targets]),
);
/** XP for verified play after the first clear, bounded per day so grinding cannot run away. */
export const REPLAY_XP = 20;
export const DAILY_REPLAY_XP_LIMIT = 10;
export const DAILY_SHOT_XP = 50;
export const EVENT_XP = 100;
export const tournaments = [
  {
    id: "precision-preseason",
    name: "Precision Open",
    kind: "coins",
    status: "open",
    subtitle: "Preseason skill challenge",
    description:
      "The same straight-pot challenge for every player. Fewest shots wins; simulated time breaks ties.",
    level: 1,
    entry: 0,
    reward: 150,
    currency: "coins",
    prize: "150 coins · first verified completion",
    rules: [
      "Free entry. Guests welcome for preseason.",
      "Pot the 1 without scratching. No ball placement.",
      "Scores are replayed and checked by the server.",
      "Rewards are granted once per player; improve your best score anytime.",
    ],
  },
  {
    id: "weekly-pro",
    name: "Weekly Pro",
    kind: "coins",
    status: "announced",
    subtitle: "Head-to-head bracket",
    description:
      "A competitive weekly bracket. Registration opens when multiplayer is ready.",
    level: 4,
    entry: 0,
    reward: 0,
    currency: "coins",
    prize: "Prize pool announced at registration",
    rules: [
      "Verified account required at launch.",
      "Bracket and final rules will be published before registration.",
    ],
  },
  {
    id: "masters-usdc",
    name: "CueMaster Masters",
    kind: "crypto",
    status: "announced",
    subtitle: "Special USDC competition",
    description:
      "A planned skill competition rewarding the best players. Entries and payouts are not open yet.",
    level: 7,
    entry: 0,
    reward: 0,
    currency: "USDC",
    prize: "USDC · funded pool to be announced",
    rules: [
      "Top-player rewards paid in USDC when the event launches.",
      "Verified account, age and regional eligibility required.",
      "Funded prize pool, placement awards and final rules published before entry.",
      "No crypto deposits or wagers. No entry fees are collected while announced.",
    ],
  },
];
export const levelOf = (xp: number) => 1 + Math.floor(xp / 100);
export const dailyKey = (d = new Date()) => d.toISOString().slice(0, 10);
